version: '3.8'

services:
  apiserver:
    build: .
    command: ./wait-for-postgres.sh db ./apiserver
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty
  db:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
